### ISSUE TITLE
iOS 11.0.1 PassDrop 2.0.1 DropBox Error v1_retired

### ISSUE THREAD

**Issue by paullinford** [rudism/passdrop#10]
I just updated to iOS 11.0.1.
I'm having an issue on an iPhone 6. I keep getting
"Dropbox Error v1_retired"
when adding database.
I deleted and reinstalled Passdrop 2.0.1.
I deleted the PassDrop2 linked app in DropBox settings.
Not sure what is going on, except that initially, the old passdrop version opened, which I thought I had deleted. It is deleted now, but the error persists.

**Comment by tihonich** [comment]
I have this issue too. Help please)

**Comment by bpharriss** [comment]
This has to do with the DropBox API used by PassDrop. PassDrop was written using V1 of the DropBox API, to allow access to DropBox files. DropBox subsequently released V2 of the API, and announced that after September 29, the V1 API would no longer work. See https://blogs.dropbox.com/developers/2017/09/api-v1-shutdown-details/ for details. 

In order to fix this, the code in PassDrop needs to be updated to use the DropBox V2 APIs.

**Comment by rudism** [comment]
My understanding is that @chadaustin is working on updating his fork (available as Passdrop 2 on the app store) to the newer API version. It's not a trivial update though, so there's no ETA on a fix.

**Comment by paullinford** [comment]
Problem is on iPhone 6, iOS 11.0.1, DropBox 64.3.4, PassDrop 2.0.1.
Odd thing is, iPad Air mini iOS 11.0.1, DropBox 64.3.4, PassDrop 2.0.1 does not have a problem, but I think I had working PassDrop 1 before going iOS 11.0.1 and then PassDrop 2.0.1.  So maybe just the initial linking broken. Once it is there, seems to work.

**Comment by chadaustin** [comment]
Hi all, @rudism is correct - I'm working on updating to the newer Dropbox API in the evenings.  No ETA on a fix, but since I'm a PassDrop user too, I'm motivated to implement a fix.  :)  I'll keep you updated when the new app has been shipped to Apple!

**Comment by chadaustin** [comment]
Hello!  Wanted you all to know I started a tracking task documenting my progress.  

https://github.com/chadaustin/passdrop/issues/1

**Comment by tihonich** [comment]
Guys! Could you share please positive experience to fix this issue. Please....

**Comment by chadaustin** [comment]
@tihonich there is no workaround for now, but I am working on a new version of the app that speaks Dropbox API v2.  You can follow progress at https://github.com/chadaustin/passdrop/issues/1

**Comment by tihonich** [comment]
@chadaustin great thanks. I will follow the developments

**Comment by paullinford** [comment]
Hi Chad, so far so good on my iPhone 6 that had the issue. It was a little squirrelly getting into Dropbox, but that might have been because of a Dropbox update too.
iPhone 6 iOS 11.0.2
Dropbox 68.2.2
Passdrop 2.0.2

**Comment by nicolaslegland** [comment]
Passdrop 2.0.2 seems to be working again on my iPhone 4S running iOS 9.3.5 (13G36).

Many thanks!

**Comment by chadaustin** [comment]
@paullinford Glad to hear it!  There was a crash on iPhone in 2.0.2 that I suspect was the squirelliness you saw during Dropbox linking.  I just uploaded 2.0.3 which should fix that.  It also fixes the crash when switching between other apps and PassDrop.

@rudism I think you can close this task in lieu of https://github.com/chadaustin/passdrop/issues/1 now. :)
